print(" meu  nome é:")
print(" Luiz Vinicius da Silva Viana:")
print("Tenho:")
print("15 anos")
print("Tenho um irmão chamado:")
print("Luis Fernando")
print("Meu animal favorito é um gato:")
print(">^.^<")
print("eu gosto de ficar jogando:")
print("[+..••]")
print("tambem gosto de ouvir musica:")
print("♪♫*•♪")
