print("PARABENS!!!!!!!!!")
print("")
print("DINOSSAUROOOOOOOOO!")
print("            __")
print("           / _)")
print("    .-^^^-/ / ")     
print(" __/       /")
print("<__.|_|-|_|")
print("")
print("OLHA O BOLINHO :D")

print(". " *11)
print("i "*11)
print("#"*21)
print("="*21)
print("#"*21)
print("="*21)
print("#"*21)
